# Do the de-bayering independent of ROS
auto_brightness: 2
auto_exposure: 2
auto_focus: 5
auto_gain: 2
auto_gamma: 0
auto_hue: 5
auto_iris: 5
auto_pan: 2
auto_saturation: 5
auto_sharpness: 5
auto_shutter: 2
auto_trigger: 0
auto_white_balance: 3
auto_zoom: 5
bayer_method: Simple
bayer_pattern: rggb
binning_x: 0
binning_y: 0
brightness: 174.0
camera_info_url: ""
exposure: 0.0
external_trigger: false
focus: 0.0
format7_color_coding: mono8
format7_packet_size: 0
frame_id: camera
frame_rate: 30.0
gain: 16.0
gamma: 0.0
guid: 00b09d0100da166d
hue: 0.0
iris: 8.0
iso_speed: 400
num_dma_buffers: 4
pan: 56.0
reset_on_open: false
roi_height: 0
roi_width: 0
saturation: 1.0
sharpness: 1.0
shutter: 520.0
software_trigger: false
time_offset: 0.0
trigger: 0.0
trigger_mode: mode_0
trigger_polarity: active_low
trigger_source: source_0
use_ros_time: false
video_mode: 640x480_mono8
white_balance_BU: 610.0
white_balance_RV: 535.0
x_offset: 0
y_offset: 0
zoom: 0.0

