auto_exposure: false
auto_frame_rate: false
auto_gain: false
auto_white_balance: true
binning: 1
blue_gain: 10
camera_id: 0
camera_intrinsics_file: ""
camera_name: camera
camera_parameters_file: ""
camera_topic: image_raw
color_mode: rgb8
exposure: 19.98588
ext_trigger_mode: false
flash_delay: 40
flash_duration: 1000
flip_lr: false
flip_upd: false
frame_rate: 30.0
gain_boost: false
green_gain: 0
image_height: 480
image_left: -1
image_top: -1
image_width: 640
master_gain: 0
pixel_clock: 25
red_gain: 0
sensor_scaling: 1.0
subsampling: 1
white_balance_blue_offset: 0
white_balance_red_offset: 0

